_mode: eth-xgaze

# key params to update the original config file in ptgaze/data/configs
device: cuda

face_detector:
  mode: face_alignment_sfd  # face_alignment_sfd, mediapipe, dlib
  dlib_model_path: src/checkpoints/shape_predictor_68_face_landmarks.dat  # if use dlib
kalman_filter:
  measure_dim: 2
  state_dim: 4
  process_noise: 0.01
  measurement_noise: 0.1
  coeff_Q: 0.5
  coeff_P: 10
gaze_estimator:
  checkpoint: src/checkpoints/eth-xgaze_resnet18.pth
  camera_params: src/config/gaze_estimation/sample_params.yaml
demo:
  use_camera: false
  display_on_screen: false
  show_head_pose: True
  use_face_pose: true
  image_path: infer_test.jpg
